name: "Deploy to NuGet"

on:
   release:
    types:
      - published


env:
  PROJECT_PATH: "nugetwithgithub.csproj"
  PACKAGE_OUTPUT_DIR: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: "https://github.com/learnedbylife/nugetwithgithub"

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Install Dotnet"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    
    - name: "Restore package"
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: "Build package"
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: "Pack project"
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIR }}

    - name: "Push package"
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIR }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}